export default {

    user:[

         { 
            username: 'test-user-1',
            email: 'test-user@example.com',
            password: '1234',
            loggedIn:false,
         },
         { 
            username: 'ts',
            email: 't@s.com',
            password: 'ts',
            loggedIn:false,
         },
    ],
    products: [],
    
    dashboardDisplay:[
      {
        "PM #": 1,
        "Merchant SKU": "AMF-1-FBA",
        "ASIN": "B005F1ATJQ",
        "Display Name": "Ancient Minerals Magnesium Bath Flakes - 1.65lb",
        "Brand": "Ancient Minerals",
        "DP Link": "Bath Flakes 1.65lb",
        "Q&A Link": "AMF-1 Q&A",
        "Reviews Page Link": "AMF-1 Review Details"
      },
      {
        "PM #": 2,
        "Merchant SKU": "AMF-4-FBA",
        "ASIN": "B06XXPLT2T",
        "Display Name": "Ancient Minerals Magnesium Bath Flakes - 4.4lb",
        "Brand": "Ancient Minerals",
        "DP Link": "Bath Flakes 4.4lb",
        "Q&A Link": "AMF-4 Q&A",
        "Reviews Page Link": "AMF-4 Review Details"
      },
      {
        "PM #": 3,
        "Merchant SKU": "AMF-8-FBA",
        "ASIN": "B00BBD508C",
        "Display Name": "Ancient Minerals Magnesium Bath Flakes - 8.0lb",
        "Brand": "Ancient Minerals",
        "DP Link": "Bath Flakes 8.0lb",
        "Q&A Link": "AMF-8 Q&A",
        "Reviews Page Link": "AMF-8 Review Details"
      },
      {
        "PM #": 4,
        "Merchant SKU": "AMFU-1-FBA",
        "ASIN": "B00JFUD1OS",
        "Display Name": "Ancient Minerals Magnesium Bath Flakes ULTRA - 1.65lb",
        "Brand": "Ancient Minerals",
        "DP Link": "Bath Flakes Ultra 1.65lb",
        "Q&A Link": "AMFU-1 Q&A",
        "Reviews Page Link": "AMFU Review Details"
      },
      {
        "PM #": 5,
        "Merchant SKU": "AMO-4-FBA",
        "ASIN": "B06XXN4T98",
        "Display Name": "Ancient Minerals Magnesium Oil - 4 oz",
        "Brand": "Ancient Minerals",
        "DP Link": "Magnesium Oil 4oz",
        "Q&A Link": "AMO-4 Q&A",
        "Reviews Page Link": "AMO-4 Review Details"
      },
      {
        "PM #": 6,
        "Merchant SKU": "AMO-8-FBA",
        "ASIN": "B001AD0HL8",
        "Display Name": "Ancient Minerals Magnesium Oil - 8 oz",
        "Brand": "Ancient Minerals",
        "DP Link": "Magnesium Oil 8oz",
        "Q&A Link": "AMO-8 Q&A",
        "Reviews Page Link": "AMO-8 Review Details"
      },
      {
        "PM #": 7,
        "Merchant SKU": "AMO-33-FBA",
        "ASIN": "B06XXN4TNR",
        "Display Name": "Ancient Minerals Magnesium Oil - 33.8 oz",
        "Brand": "Ancient Minerals",
        "DP Link": "Magnesium Oil 33oz",
        "Q&A Link": "AMO-33 Q&A",
        "Reviews Page Link": "AMO-33 Review Details"
      },
      {
        "PM #": 8,
        "Merchant SKU": "AMOU-4-FBA",
        "ASIN": "B06XXPSJGT",
        "Display Name": "Ancient Minerals Magnesium Oil ULTRA - 4oz",
        "Brand": "Ancient Minerals",
        "DP Link": "Magnesium Oil Ultra 4",
        "Q&A Link": "AMOU-4 Q&A",
        "Reviews Page Link": "AMOU-4 Review Details"
      },
      {
        "PM #": 9,
        "Merchant SKU": "AMOU-8-FBA",
        "ASIN": "B008JSJ9HU",
        "Display Name": "Ancient Minerals Magnesium Oil ULTRA - 8oz",
        "Brand": "Ancient Minerals",
        "DP Link": "Magnesium Oil Ultra 8",
        "Q&A Link": "AMOU-8 Q&A",
        "Reviews Page Link": "AMOU-8 Review Details"
      },
      {
        "PM #": 10,
        "Merchant SKU": "AMOU-33-FBA",
        "ASIN": "B06XXSYX2W",
        "Display Name": "Ancient Minerals Magnesium Oil ULTRA - 33.8oz",
        "Brand": "Ancient Minerals",
        "DP Link": "Magnesium Oil Ultra 33oz",
        "Q&A Link": "AMOU-33 Q&A",
        "Reviews Page Link": "AMOU-33 Review Details"
      },
      {
        "PM #": 11,
        "Merchant SKU": "AML-5-FBA",
        "ASIN": "B06XXP8YRL",
        "Display Name": "Ancient Minerals Magnesium Lotion - 5 oz.",
        "Brand": "Ancient Minerals",
        "DP Link": "Magnesium Lotion",
        "Q&A Link": "AML-5 Q&A",
        "Reviews Page Link": "AML-5 Review Details"
      },
      {
        "PM #": 12,
        "Merchant SKU": "AMLU-5-FBA",
        "ASIN": "B06XXR6PRD",
        "Display Name": "Ancient Minerals Magnesium Lotion ULTRA - 5oz",
        "Brand": "Ancient Minerals",
        "DP Link": "Magnesium Lotion Ultra",
        "Q&A Link": "AMLU-5 Q&A",
        "Reviews Page Link": "AMLU-5 Review Details"
      },
      {
        "PM #": 13,
        "Merchant SKU": "AMLG-2-FBA",
        "ASIN": "B00BN9PFUW",
        "Display Name": "Ancient Minerals Magnesium Lotion Goodnight - 2.5oz",
        "Brand": "Ancient Minerals",
        "DP Link": "Magnesium Lotion Goodnight",
        "Q&A Link": "AMLG-2 Q&A",
        "Reviews Page Link": "AMLG-2 Review Details"
      },
      {
        "PM #": 14,
        "Merchant SKU": "AMG-8-FBA",
        "ASIN": "B001RJ7MRM",
        "Display Name": "Ancient Minerals Magnesium Gel - 8oz",
        "Brand": "Ancient Minerals",
        "DP Link": "Magnesium Gel",
        "Q&A Link": "AMG-8 Q&A",
        "Reviews Page Link": "AMG-8 Review Details"
      },
      {
        "PM #": 15,
        "Merchant SKU": "AMGU-8-FBA",
        "ASIN": "B00JIN7DVY",
        "Display Name": "Ancient Minerals Magnesium Gel Ultra- 8oz",
        "Brand": "Ancient Minerals",
        "DP Link": "Magnesium Gel Ultra",
        "Q&A Link": "AMGU-8 Q&A",
        "Reviews Page Link": "AMGU-8 Review Details"
      },
      {
        "PM #": 16,
        "Merchant SKU": "TF-60-FBA",
        "ASIN": "B07G7GK2N1",
        "Display Name": "Enviromedica Terraflora Soil-Based Probiotic",
        "Brand": "Enviromedica",
        "DP Link": "Terraflora Probiotic",
        "Q&A Link": "TF-60 Q&A",
        "Reviews Page Link": "TF-60 Review Details"
      },
      {
        "PM #": 17,
        "Merchant SKU": "TFAC-60-FBA",
        "ASIN": "B082MTLLRH",
        "Display Name": "Enviromedica Terraflora Advanced Care Daily Probiotic",
        "Brand": "Enviromedica",
        "DP Link": "Terraflora Advanced Care",
        "Q&A Link": "TFAC-60 Q&A",
        "Reviews Page Link": "TFAC-60 Review Details"
      },
      {
        "PM #": 18,
        "Merchant SKU": "TFDI-60-FBA",
        "ASIN": "B082MT873N",
        "Display Name": "Enviromedica Terraflora Deep Immune Synbiotic",
        "Brand": "Enviromedica",
        "DP Link": "Terraflora Deep Immune",
        "Q&A Link": "TFDI-60 Q&A",
        "Reviews Page Link": "TFDI-60 Review Details"
      },
      {
        "PM #": 19,
        "Merchant SKU": "TFWD-60-FBA",
        "ASIN": "B082MSTTPX",
        "Display Name": "Enviromedica Terraflora Women's Daily Synbiotic",
        "Brand": "Enviromedica",
        "DP Link": "Terraflor Womens's Daily",
        "Q&A Link": "TFWD-60 Q&A",
        "Reviews Page Link": "TFWD-60 Review Details"
      },
      {
        "PM #": 20,
        "Merchant SKU": "MCB-4-FBA",
        "ASIN": "B00X7RCW4A",
        "Display Name": "Enviromedica Magnetic Clay Natural (4.62lb Jar)",
        "Brand": "Enviromedica",
        "DP Link": "Magnetic Clay Bath",
        "Q&A Link": "MCB-4 Q&A",
        "Reviews Page Link": "MCB-4 Review Details"
      },
      {
        "PM #": 21,
        "Merchant SKU": "CAR-120-FBA",
        "ASIN": "B07H7VM5Q8",
        "Display Name": "Enviromedica Tracheal Cartilage Collagen (120ct)",
        "Brand": "Enviromedica",
        "DP Link": "Cartilage Collagen",
        "Q&A Link": "CAR-120 Q&A",
        "Reviews Page Link": "CAR-120 Review Details"
      },
      {
        "PM #": 22,
        "Merchant SKU": "BLV-180-FBA",
        "ASIN": "B07H7VBFF1",
        "Display Name": "Enviromedica Beef Liver with Preformed Vitamin A (180ct)",
        "Brand": "Enviromedica",
        "DP Link": "Beef Liver Capsules",
        "Q&A Link": "BLV-120 Q&A",
        "Reviews Page Link": "BLV-180 Review Details"
      },
      {
        "PM #": 23,
        "Merchant SKU": "MAR-120-FBA",
        "ASIN": "B082XHGHM3",
        "Display Name": "Enviromedica Bone Marrow (120ct)",
        "Brand": "Enviromedica",
        "DP Link": "Bone Marrow",
        "Q&A Link": "MAR-120 Q&A",
        "Reviews Page Link": "MAR-120 Review Details"
      },
      {
        "PM #": 24,
        "Merchant SKU": "ORG-150-FBA",
        "ASIN": "B082XJVB9S",
        "Display Name": "Enviromedica Organ Complex (150ct)",
        "Brand": "Enviromedica",
        "DP Link": "Organ Complex",
        "Q&A Link": "ORD-150 Q&A",
        "Reviews Page Link": "ORG-150 Review Details"
      },
      {
        "PM #": 25,
        "Merchant SKU": "AMOS-4-FBA",
        "ASIN": "B07HZPZKNC",
        "Display Name": "Ancient Minerals Oil Sensitive - 4oz",
        "Brand": "Ancient Minerals",
        "DP Link": "Oil Sensitive",
        "Q&A Link": "AMOS-4 Q&A",
        "Reviews Page Link": "AMOS-4 Review Details"
      },
      {
        "PM #": 26,
        "Merchant SKU": "AMOSP-4-FBA",
        "ASIN": "B07JH84532",
        "Display Name": "Ancient Minerals Oil Sensitive Plus - 4oz",
        "Brand": "Ancient Minerals",
        "DP Link": "Oil Senstitve+",
        "Q&A Link": "AMOSP-4 Q&A",
        "Reviews Page Link": "AMOSP-4 Review Details"
      },
      {
        "PM #": 27,
        "Merchant SKU": "AMFB-150-FBA",
        "ASIN": "B07KY3N9SF",
        "Display Name": "Ancient Minerals Inflatable Foot Bath Kit",
        "Brand": "Ancient Minerals",
        "DP Link": "Inflatable Footbath",
        "Q&A Link": "AMFB-150 Q&A",
        "Reviews Page Link": "AMFB-150 Review Details"
      },
      {
        "PM #": 28,
        "Merchant SKU": "AMF-150-6-FBA",
        "ASIN": "B07MR2MDW8",
        "Display Name": "Ancient Minerals Single Use Pouch, Pack of 6",
        "Brand": "Ancient Minerals",
        "DP Link": "Single Use Pouches x6pack)",
        "Q&A Link": "AMF-150-6 Q&A",
        "Reviews Page Link": "AMF-150-6 Review Details"
      },
      {
        "PM #": 29,
        "Merchant SKU": "TMT-68-FBA",
        "ASIN": "1450283543",
        "Display Name": "Ancient Minerals Transdermal Magnesium Book",
        "Brand": "Enviromedica",
        "DP Link": "n/a",
        "Q&A Link": "n/a",
        "Reviews Page Link": "n/a"
      },
     ],

    inventory: [
      {
        "sku": "AMF-1-FBA",
        "fnsku": "X001Y1DPYN",
        "asin": "B005F1ATJQ",
        "product-name": "Ancient Minerals Magnesium Bath Flakes of Pure Genuine Zechstein Chloride - Resealable Magnesium Supplement Bag That Will Outperform Leading Epsom Salts (26.4 Ounce)",
        "condition": "New",
        "your-price": 9.95,
        "mfn-listing-exists": "No",
        "mfn-fulfillable-quantity": "",
        "afn-listing-exists": "Yes",
        "afn-warehouse-quantity": 2695,
        "afn-fulfillable-quantity": 963,
        "afn-unsellable-quantity": 6,
        "afn-reserved-quantity": 1718,
        "afn-total-quantity": 3445,
        "per-unit-volume": 0.05,
        "afn-inbound-working-quantity": 720,
        "afn-inbound-shipped-quantity": 0,
        "afn-inbound-receiving-quantity": 30,
        "afn-researching-quantity": 8
      },
      {
        "sku": "AMF-150-6-FBA",
        "fnsku": "X00200W4L7",
        "asin": "B07MR2MDW8",
        "product-name": "Ancient Minerals Magnesium Bath Flakes Single-Use Magnesium Chloride Pouches (0.33lb Bag, Pack of 6)",
        "condition": "New",
        "your-price": 18.97,
        "mfn-listing-exists": "No",
        "mfn-fulfillable-quantity": "",
        "afn-listing-exists": "Yes",
        "afn-warehouse-quantity": 150,
        "afn-fulfillable-quantity": 141,
        "afn-unsellable-quantity": 0,
        "afn-reserved-quantity": 9,
        "afn-total-quantity": 150,
        "per-unit-volume": 0.12,
        "afn-inbound-working-quantity": 0,
        "afn-inbound-shipped-quantity": 0,
        "afn-inbound-receiving-quantity": 0,
        "afn-researching-quantity": 0
      },
      {
        "sku": "AMF-4-FBA",
        "fnsku": "X001Y1SXAJ",
        "asin": "B06XXPLT2T",
        "product-name": "Ancient Minerals Magnesium Bath Flakes of Pure Genuine Zechstein Chloride - Resealable Magnesium Supplement Bag That Will Outperform Leading Epsom Salts (4.4 lb)",
        "condition": "New",
        "your-price": 19.95,
        "mfn-listing-exists": "No",
        "mfn-fulfillable-quantity": "",
        "afn-listing-exists": "Yes",
        "afn-warehouse-quantity": 1559,
        "afn-fulfillable-quantity": 644,
        "afn-unsellable-quantity": 5,
        "afn-reserved-quantity": 900,
        "afn-total-quantity": 2427,
        "per-unit-volume": 0.14,
        "afn-inbound-working-quantity": 864,
        "afn-inbound-shipped-quantity": 0,
        "afn-inbound-receiving-quantity": 4,
        "afn-researching-quantity": 10
      },
      {
        "sku": "AMF-8-FBA",
        "fnsku": "X001Y1TPBZ",
        "asin": "B00BBD508C",
        "product-name": "Ancient Minerals Magnesium Bath Flakes of Pure Genuine Zechstein Chloride - Resealable Magnesium Supplement Bag That Will Outperform Leading Epsom Salts (8 lb)",
        "condition": "New",
        "your-price": 29.95,
        "mfn-listing-exists": "No",
        "mfn-fulfillable-quantity": "",
        "afn-listing-exists": "Yes",
        "afn-warehouse-quantity": 7254,
        "afn-fulfillable-quantity": 6160,
        "afn-unsellable-quantity": 36,
        "afn-reserved-quantity": 1019,
        "afn-total-quantity": 10134,
        "per-unit-volume": 0.23,
        "afn-inbound-working-quantity": 2880,
        "afn-inbound-shipped-quantity": 0,
        "afn-inbound-receiving-quantity": 0,
        "afn-researching-quantity": 39
      },
      {
        "sku": "AMFB-150-FBA",
        "fnsku": "X001YW0SER",
        "asin": "B07KY3N9SF",
        "product-name": "Ancient Minerals Inflatable Foot Bath Kit with Single-Use Magnesium Chloride Flakes Pouch - Great for Travel or at-Home Spa",
        "condition": "New",
        "your-price": 19.95,
        "mfn-listing-exists": "No",
        "mfn-fulfillable-quantity": "",
        "afn-listing-exists": "Yes",
        "afn-warehouse-quantity": 15,
        "afn-fulfillable-quantity": 14,
        "afn-unsellable-quantity": 1,
        "afn-reserved-quantity": 0,
        "afn-total-quantity": 143,
        "per-unit-volume": 0.08,
        "afn-inbound-working-quantity": 0,
        "afn-inbound-shipped-quantity": 128,
        "afn-inbound-receiving-quantity": 0,
        "afn-researching-quantity": 0
      },
      {
        "sku": "AMFU-1-FBA",
        "fnsku": "X001XM9939",
        "asin": "B00JFUD1OS",
        "product-name": "Ancient Minerals Magnesium Bath Flakes Ultra with OptiMSM - Resealable Magnesium Supplement Bag of Zechstein Chloride with Proven Better Absorption Than Epsom Bath Salt (1.65 lb)",
        "condition": "New",
        "your-price": 12.75,
        "mfn-listing-exists": "No",
        "mfn-fulfillable-quantity": "",
        "afn-listing-exists": "Yes",
        "afn-warehouse-quantity": 2057,
        "afn-fulfillable-quantity": 195,
        "afn-unsellable-quantity": 4,
        "afn-reserved-quantity": 1819,
        "afn-total-quantity": 3497,
        "per-unit-volume": 0.05,
        "afn-inbound-working-quantity": 1440,
        "afn-inbound-shipped-quantity": 0,
        "afn-inbound-receiving-quantity": 0,
        "afn-researching-quantity": 39
      },
      {
        "sku": "AMG-8-FBA",
        "fnsku": "X001Y1IINL",
        "asin": "B001RJ7MRM",
        "product-name": "Ancient Minerals Magnesium Gel - 8oz Tube - Pure Genuine Zechstein Magnesium Chloride - Best for Massage, Topical Skin Dermal Absorption",
        "condition": "Unknown",
        "your-price": null,
        "mfn-listing-exists": "",
        "mfn-fulfillable-quantity": "",
        "afn-listing-exists": "",
        "afn-warehouse-quantity": 2,
        "afn-fulfillable-quantity": 0,
        "afn-unsellable-quantity": 1,
        "afn-reserved-quantity": 1,
        "afn-total-quantity": 2,
        "per-unit-volume": 0.01,
        "afn-inbound-working-quantity": 0,
        "afn-inbound-shipped-quantity": 0,
        "afn-inbound-receiving-quantity": 0,
        "afn-researching-quantity": 0
      },
      {
        "sku": "AMGU-8-FBA",
        "fnsku": "X001Y1WR0B",
        "asin": "B00JIN7DVY",
        "product-name": "Ancient Minerals Magnesium Gel Ultra with OptiMSM and Aloe Vera - Topical Magnesium Gel Formula with MSM Best Used for Dermal Skin Absorption and Massage Therapy (8oz)",
        "condition": "New",
        "your-price": 21.97,
        "mfn-listing-exists": "No",
        "mfn-fulfillable-quantity": "",
        "afn-listing-exists": "Yes",
        "afn-warehouse-quantity": 498,
        "afn-fulfillable-quantity": 2,
        "afn-unsellable-quantity": 8,
        "afn-reserved-quantity": 480,
        "afn-total-quantity": 534,
        "per-unit-volume": 0.01,
        "afn-inbound-working-quantity": 0,
        "afn-inbound-shipped-quantity": 0,
        "afn-inbound-receiving-quantity": 36,
        "afn-researching-quantity": 8
      },
      {
        "sku": "AML-5-FBA",
        "fnsku": "X001Y1TXI5",
        "asin": "B06XXP8YRL",
        "product-name": "Ancient Minerals Magnesium Lotion of Pure Genuine Zechstein Magnesium Chloride - Best used for Topical Skin Application on Sensitive Skin (5oz)",
        "condition": "New",
        "your-price": 19.95,
        "mfn-listing-exists": "No",
        "mfn-fulfillable-quantity": "",
        "afn-listing-exists": "Yes",
        "afn-warehouse-quantity": 2548,
        "afn-fulfillable-quantity": 29,
        "afn-unsellable-quantity": 21,
        "afn-reserved-quantity": 2490,
        "afn-total-quantity": 4404,
        "per-unit-volume": 0.02,
        "afn-inbound-working-quantity": 1600,
        "afn-inbound-shipped-quantity": 256,
        "afn-inbound-receiving-quantity": 0,
        "afn-researching-quantity": 8
      },
      {
        "sku": "AMLG-2-FBA",
        "fnsku": "X001Y1FS3T",
        "asin": "B00BN9PFUW",
        "product-name": "Ancient Minerals Goodnight Magnesium Lotion with Melatonin and OptiMSM - Night Cream of Topical Nighttime Moisturizing Lotion formulated for Bedtime Absorption (2.5oz)",
        "condition": "New",
        "your-price": 28.97,
        "mfn-listing-exists": "No",
        "mfn-fulfillable-quantity": "",
        "afn-listing-exists": "Yes",
        "afn-warehouse-quantity": 977,
        "afn-fulfillable-quantity": 88,
        "afn-unsellable-quantity": 5,
        "afn-reserved-quantity": 882,
        "afn-total-quantity": 1233,
        "per-unit-volume": 0.02,
        "afn-inbound-working-quantity": 0,
        "afn-inbound-shipped-quantity": 256,
        "afn-inbound-receiving-quantity": 0,
        "afn-researching-quantity": 2
      },
      {
        "sku": "AMLU-5-FBA",
        "fnsku": "X001Y2CTJT",
        "asin": "B06XXR6PRD",
        "product-name": "Ancient Minerals Magnesium Lotion ULTRA with MSM - Pure Genuine Zechstein Magnesium Lotion Supplement with MSM for Topical Application (5oz)",
        "condition": "New",
        "your-price": 21.95,
        "mfn-listing-exists": "No",
        "mfn-fulfillable-quantity": "",
        "afn-listing-exists": "Yes",
        "afn-warehouse-quantity": 1603,
        "afn-fulfillable-quantity": 1327,
        "afn-unsellable-quantity": 6,
        "afn-reserved-quantity": 254,
        "afn-total-quantity": 2563,
        "per-unit-volume": 0.02,
        "afn-inbound-working-quantity": 960,
        "afn-inbound-shipped-quantity": 0,
        "afn-inbound-receiving-quantity": 0,
        "afn-researching-quantity": 16
      },
      {
        "sku": "AMO-33-FBA",
        "fnsku": "X001Y1BVKD",
        "asin": "B06XXN4TNR",
        "product-name": "Ancient Minerals Magnesium Oil Refill Bottle of Pure Genuine Zechstein Magnesium Chloride - Topical Magnesium Supplement for Skin Application and Dermal Absorption (33.8oz)",
        "condition": "New",
        "your-price": 39.97,
        "mfn-listing-exists": "No",
        "mfn-fulfillable-quantity": "",
        "afn-listing-exists": "Yes",
        "afn-warehouse-quantity": 479,
        "afn-fulfillable-quantity": 109,
        "afn-unsellable-quantity": 1,
        "afn-reserved-quantity": 365,
        "afn-total-quantity": 479,
        "per-unit-volume": 0.06,
        "afn-inbound-working-quantity": 0,
        "afn-inbound-shipped-quantity": 0,
        "afn-inbound-receiving-quantity": 0,
        "afn-researching-quantity": 4
      },
      {
        "sku": "AMO-4-FBA",
        "fnsku": "X001Y1BOUP",
        "asin": "B06XXN4T98",
        "product-name": "Ancient Minerals Magnesium Oil Spray Bottle of Pure Genuine Zechstein Magnesium Chloride - Topical Magnesium Supplement for Skin Application and Dermal Absorption (4oz)",
        "condition": "New",
        "your-price": 11.97,
        "mfn-listing-exists": "No",
        "mfn-fulfillable-quantity": "",
        "afn-listing-exists": "Yes",
        "afn-warehouse-quantity": 879,
        "afn-fulfillable-quantity": 737,
        "afn-unsellable-quantity": 9,
        "afn-reserved-quantity": 82,
        "afn-total-quantity": 1199,
        "per-unit-volume": 0.02,
        "afn-inbound-working-quantity": 320,
        "afn-inbound-shipped-quantity": 0,
        "afn-inbound-receiving-quantity": 0,
        "afn-researching-quantity": 51
      },
      {
        "sku": "AMO-8-FBA",
        "fnsku": "X001Y15BMR",
        "asin": "B001AD0HL8",
        "product-name": "Ancient Minerals Magnesium Oil Spray Bottle of Pure Genuine Zechstein Magnesium Chloride - Topical Magnesium Supplement for Skin Application and Dermal Absorption (8 Fl Oz)",
        "condition": "New",
        "your-price": 18.97,
        "mfn-listing-exists": "No",
        "mfn-fulfillable-quantity": "",
        "afn-listing-exists": "Yes",
        "afn-warehouse-quantity": 2219,
        "afn-fulfillable-quantity": 536,
        "afn-unsellable-quantity": 4,
        "afn-reserved-quantity": 1644,
        "afn-total-quantity": 3900,
        "per-unit-volume": 0.02,
        "afn-inbound-working-quantity": 1600,
        "afn-inbound-shipped-quantity": 0,
        "afn-inbound-receiving-quantity": 81,
        "afn-researching-quantity": 35
      },
      {
        "sku": "AMOS-4-FBA",
        "fnsku": "X001Y1F8JN",
        "asin": "B07HZPZKNC",
        "product-name": "Ancient Minerals Magnesium Oil Spray Sensitive – All-New Sensitive Formula with Allantoin, Organic Chamomile, and Organic Aloe Vera (4oz)",
        "condition": "New",
        "your-price": 11.95,
        "mfn-listing-exists": "No",
        "mfn-fulfillable-quantity": "",
        "afn-listing-exists": "Yes",
        "afn-warehouse-quantity": 473,
        "afn-fulfillable-quantity": 453,
        "afn-unsellable-quantity": 2,
        "afn-reserved-quantity": 18,
        "afn-total-quantity": 473,
        "per-unit-volume": 0.01,
        "afn-inbound-working-quantity": 0,
        "afn-inbound-shipped-quantity": 0,
        "afn-inbound-receiving-quantity": 0,
        "afn-researching-quantity": 0
      },
      {
        "sku": "AMOSP-4-FBA",
        "fnsku": "X001Y2LU9T",
        "asin": "B07JH84532",
        "product-name": "Ancient Minerals Magnesium Oil Spray Sensitive Plus – All-New Sensitive+ Formula Oil with Avena Sativa (Oat Aventhramides), Nopal Cactus, Organic Chamomile, and Allantoin (4oz)",
        "condition": "New",
        "your-price": 14.97,
        "mfn-listing-exists": "No",
        "mfn-fulfillable-quantity": "",
        "afn-listing-exists": "Yes",
        "afn-warehouse-quantity": 330,
        "afn-fulfillable-quantity": 328,
        "afn-unsellable-quantity": 1,
        "afn-reserved-quantity": 1,
        "afn-total-quantity": 330,
        "per-unit-volume": 0.02,
        "afn-inbound-working-quantity": 0,
        "afn-inbound-shipped-quantity": 0,
        "afn-inbound-receiving-quantity": 0,
        "afn-researching-quantity": 0
      },
      {
        "sku": "AMOU-33-FBA",
        "fnsku": "X001Y1H7GP",
        "asin": "B06XXSYX2W",
        "product-name": "Ancient Minerals Magnesium Oil Ultra with OptiMSM, Refill 33.8 oz. - Pure Genuine Zechstein Magnesium Chloride Supplement with MSM - Best Topical Skin Application for Dermal Absorption",
        "condition": "New",
        "your-price": 43.95,
        "mfn-listing-exists": "No",
        "mfn-fulfillable-quantity": "",
        "afn-listing-exists": "Yes",
        "afn-warehouse-quantity": 265,
        "afn-fulfillable-quantity": 222,
        "afn-unsellable-quantity": 2,
        "afn-reserved-quantity": 41,
        "afn-total-quantity": 265,
        "per-unit-volume": 0.06,
        "afn-inbound-working-quantity": 0,
        "afn-inbound-shipped-quantity": 0,
        "afn-inbound-receiving-quantity": 0,
        "afn-researching-quantity": 0
      },
      {
        "sku": "AMOU-4-FBA",
        "fnsku": "X001Y174QD",
        "asin": "B06XXPSJGT",
        "product-name": "Ancient Minerals Magnesium Oil Spray Ultra with MSM - a Pure Zechstein Topical Magnesium Chloride Supplement with The Added Benefits of OptiMSM (4oz)",
        "condition": "New",
        "your-price": 12.95,
        "mfn-listing-exists": "No",
        "mfn-fulfillable-quantity": "",
        "afn-listing-exists": "Yes",
        "afn-warehouse-quantity": 942,
        "afn-fulfillable-quantity": 878,
        "afn-unsellable-quantity": 1,
        "afn-reserved-quantity": 63,
        "afn-total-quantity": 942,
        "per-unit-volume": 0.01,
        "afn-inbound-working-quantity": 0,
        "afn-inbound-shipped-quantity": 0,
        "afn-inbound-receiving-quantity": 0,
        "afn-researching-quantity": 0
      },
      {
        "sku": "AMOU-8-FBA",
        "fnsku": "X001Y1DK1L",
        "asin": "B008JSJ9HU",
        "product-name": "Ancient Minerals Magnesium Oil Spray Ultra with MSM - a Pure Zechstein Topical Magnesium Chloride Supplement with The Added Benefits of OptiMSM (8oz)",
        "condition": "New",
        "your-price": 21.95,
        "mfn-listing-exists": "No",
        "mfn-fulfillable-quantity": "",
        "afn-listing-exists": "Yes",
        "afn-warehouse-quantity": 517,
        "afn-fulfillable-quantity": 466,
        "afn-unsellable-quantity": 6,
        "afn-reserved-quantity": 40,
        "afn-total-quantity": 1477,
        "per-unit-volume": 0.02,
        "afn-inbound-working-quantity": 960,
        "afn-inbound-shipped-quantity": 0,
        "afn-inbound-receiving-quantity": 0,
        "afn-researching-quantity": 5
      },
      {
        "sku": "BLV-180-FBA",
        "fnsku": "X001Y6KIB1",
        "asin": "B07H7VBFF1",
        "product-name": "Enviromedica Freeze Dried Beef Liver Natural Energy Supplement Capsules of Pure Grass-Fed, Pastured, New Zealand Bovine with Preformed Vitamin A (180ct)",
        "condition": "New",
        "your-price": 29.95,
        "mfn-listing-exists": "No",
        "mfn-fulfillable-quantity": "",
        "afn-listing-exists": "Yes",
        "afn-warehouse-quantity": 221,
        "afn-fulfillable-quantity": 132,
        "afn-unsellable-quantity": 3,
        "afn-reserved-quantity": 82,
        "afn-total-quantity": 671,
        "per-unit-volume": 0.02,
        "afn-inbound-working-quantity": 450,
        "afn-inbound-shipped-quantity": 0,
        "afn-inbound-receiving-quantity": 0,
        "afn-researching-quantity": 4
      },
      {
        "sku": "CAR-120-FBA",
        "fnsku": "X001Y70F0T",
        "asin": "B07H7VM5Q8",
        "product-name": "Enviromedica Tracheal Cartilage Collagen Supplement Capsules of Undenatured Type II Bovine Collagen Protein sourced from Grass Fed New Zealand Beef (120ct)",
        "condition": "New",
        "your-price": 39.95,
        "mfn-listing-exists": "No",
        "mfn-fulfillable-quantity": "",
        "afn-listing-exists": "Yes",
        "afn-warehouse-quantity": 481,
        "afn-fulfillable-quantity": 171,
        "afn-unsellable-quantity": 4,
        "afn-reserved-quantity": 306,
        "afn-total-quantity": 751,
        "per-unit-volume": 0.02,
        "afn-inbound-working-quantity": 270,
        "afn-inbound-shipped-quantity": 0,
        "afn-inbound-receiving-quantity": 0,
        "afn-researching-quantity": 0
      },
      {
        "sku": "MAR-120-FBA",
        "fnsku": "X002F1TRRP",
        "asin": "B082XHGHM3",
        "product-name": "Enviromedica Freeze-Dried Bone Marrow Complex with Cartilage and MCHA Whole Bone from Grass-Fed Pastured New Zealand Bovine (120ct)",
        "condition": "New",
        "your-price": 29.95,
        "mfn-listing-exists": "No",
        "mfn-fulfillable-quantity": "",
        "afn-listing-exists": "Yes",
        "afn-warehouse-quantity": 122,
        "afn-fulfillable-quantity": 104,
        "afn-unsellable-quantity": 0,
        "afn-reserved-quantity": 18,
        "afn-total-quantity": 302,
        "per-unit-volume": 0.03,
        "afn-inbound-working-quantity": 180,
        "afn-inbound-shipped-quantity": 0,
        "afn-inbound-receiving-quantity": 0,
        "afn-researching-quantity": 0
      },
      {
        "sku": "MCB-4-FBA",
        "fnsku": "X0022GEJRV",
        "asin": "B00X7RCW4A",
        "product-name": "Enviromedica Magnetic Clay Natural Detox Bath Cleanse – Ancient Sodium and Calcium Bentonite Clay Powder with Himalayan Pink Salt for Detoxification of Harmful Toxins and Environmental Allergens",
        "condition": "New",
        "your-price": 39.95,
        "mfn-listing-exists": "No",
        "mfn-fulfillable-quantity": "",
        "afn-listing-exists": "Yes",
        "afn-warehouse-quantity": 324,
        "afn-fulfillable-quantity": 267,
        "afn-unsellable-quantity": 4,
        "afn-reserved-quantity": 50,
        "afn-total-quantity": 724,
        "per-unit-volume": 0.11,
        "afn-inbound-working-quantity": 400,
        "afn-inbound-shipped-quantity": 0,
        "afn-inbound-receiving-quantity": 0,
        "afn-researching-quantity": 3
      },
      {
        "sku": "ORG-150-FBA",
        "fnsku": "X002F1TRRZ",
        "asin": "B082XJVB9S",
        "product-name": "Enviromedica Grass-Fed Organ Complex: Freeze-Dried Beef Liver, Kidney, Heart, and Pancreas (150ct)",
        "condition": "New",
        "your-price": 29.95,
        "mfn-listing-exists": "No",
        "mfn-fulfillable-quantity": "",
        "afn-listing-exists": "Yes",
        "afn-warehouse-quantity": 316,
        "afn-fulfillable-quantity": 175,
        "afn-unsellable-quantity": 2,
        "afn-reserved-quantity": 139,
        "afn-total-quantity": 316,
        "per-unit-volume": 0.02,
        "afn-inbound-working-quantity": 0,
        "afn-inbound-shipped-quantity": 0,
        "afn-inbound-receiving-quantity": 0,
        "afn-researching-quantity": 0
      },
      {
        "sku": "TF-60-FBA",
        "fnsku": "X001XNSYRF",
        "asin": "B07G7GK2N1",
        "product-name": "Enviromedica Terraflora Daily Care SBO Probiotic + Prebiotic Supplement - a Soil Based Shelf Stable Bacillus Spore Form Synbiotic formulated to Assist with Complete Gut Health (60ct)",
        "condition": "New",
        "your-price": 49.95,
        "mfn-listing-exists": "No",
        "mfn-fulfillable-quantity": "",
        "afn-listing-exists": "Yes",
        "afn-warehouse-quantity": 378,
        "afn-fulfillable-quantity": 89,
        "afn-unsellable-quantity": 8,
        "afn-reserved-quantity": 279,
        "afn-total-quantity": 3078,
        "per-unit-volume": 0.01,
        "afn-inbound-working-quantity": 1008,
        "afn-inbound-shipped-quantity": 0,
        "afn-inbound-receiving-quantity": 1692,
        "afn-researching-quantity": 2
      },
      {
        "sku": "TFAC-60-FBA",
        "fnsku": "X002F1YRQB",
        "asin": "B082MTLLRH",
        "product-name": "Enviromedica Terraflora Advanced Care SBO Probiotic + Prebiotic Supplement - a Soil Based Shelf Stable Bacillus Spore Synbiotic with Patented PreforPro Phage Complex (60ct)",
        "condition": "New",
        "your-price": 59.95,
        "mfn-listing-exists": "No",
        "mfn-fulfillable-quantity": "",
        "afn-listing-exists": "Yes",
        "afn-warehouse-quantity": 834,
        "afn-fulfillable-quantity": 829,
        "afn-unsellable-quantity": 2,
        "afn-reserved-quantity": 2,
        "afn-total-quantity": 834,
        "per-unit-volume": 0.01,
        "afn-inbound-working-quantity": 0,
        "afn-inbound-shipped-quantity": 0,
        "afn-inbound-receiving-quantity": 0,
        "afn-researching-quantity": 1
      },
      {
        "sku": "TFDI-60-FBA",
        "fnsku": "X002F1YRQL",
        "asin": "B082MT873N",
        "product-name": "Enviromedica Terraflora Deep Immune SBO Probiotic + Prebiotic Supplement - a Soil Based Shelf Stable Bacillus Spore Form Synbiotic with LC-Plasma – a Powerful Immune Booster (60ct)",
        "condition": "New",
        "your-price": 59.95,
        "mfn-listing-exists": "No",
        "mfn-fulfillable-quantity": "",
        "afn-listing-exists": "Yes",
        "afn-warehouse-quantity": 289,
        "afn-fulfillable-quantity": 274,
        "afn-unsellable-quantity": 5,
        "afn-reserved-quantity": 10,
        "afn-total-quantity": 577,
        "per-unit-volume": 0.01,
        "afn-inbound-working-quantity": 288,
        "afn-inbound-shipped-quantity": 0,
        "afn-inbound-receiving-quantity": 0,
        "afn-researching-quantity": 0
      },
      {
        "sku": "TFWD-60-FBA",
        "fnsku": "X002F28XBF",
        "asin": "B082MSTTPX",
        "product-name": "Enviromedica Terraflora Women’s Daily SBO Probiotic + Prebiotic Supplement - a Soil Based Bacillus Spore Form Synbiotic with Organic Cranberry to Support and a Healthy Urinary Tract (60ct)",
        "condition": "New",
        "your-price": 49.95,
        "mfn-listing-exists": "No",
        "mfn-fulfillable-quantity": "",
        "afn-listing-exists": "Yes",
        "afn-warehouse-quantity": 1012,
        "afn-fulfillable-quantity": 993,
        "afn-unsellable-quantity": 1,
        "afn-reserved-quantity": 18,
        "afn-total-quantity": 1012,
        "per-unit-volume": 0.01,
        "afn-inbound-working-quantity": 0,
        "afn-inbound-shipped-quantity": 0,
        "afn-inbound-receiving-quantity": 0,
        "afn-researching-quantity": 0
      },
      {
        "sku": "TMT-68-FBA",
        "fnsku": "X001XKXPIL",
        "asin": "1450283543",
        "product-name": "Transdermal Magnesium Therapy: A New Modality for the Maintenance of Health",
        "condition": "New",
        "your-price": 15.99,
        "mfn-listing-exists": "No",
        "mfn-fulfillable-quantity": "",
        "afn-listing-exists": "Yes",
        "afn-warehouse-quantity": 88,
        "afn-fulfillable-quantity": 83,
        "afn-unsellable-quantity": 0,
        "afn-reserved-quantity": 5,
        "afn-total-quantity": 88,
        "per-unit-volume": 0.03,
        "afn-inbound-working-quantity": 0,
        "afn-inbound-shipped-quantity": 0,
        "afn-inbound-receiving-quantity": 0,
        "afn-researching-quantity": 0
      },
     ],



    sales: [
      {
        "(Child) ASIN": "B00BBD508C",
        "Title": "Ancient Minerals Magnesium Bath Flakes of Pure Genuine Zechstein Chloride - Resealable Magnesium Supplement Bag That Will Outperform Leading Epsom Salts (8 lb)",
        "Sessions": "5,213",
        "Session Percentage": "13.34%",
        "Page Views": "8,504",
        "Page Views Percentage": "14.36%",
        "Buy Box Percentage": "92%",
        "Units Ordered": "4,698",
        "Units Ordered - B2B": 70,
        "Unit Session Percentage": "90.12%",
        "Unit Session Percentage - B2B": "1.34%",
        "Ordered Product Sales": "$148,786.04 ",
        "Ordered Product Sales - B2B": "$2,217.24 ",
        "Total Order Items": "3,915",
        "Total Order Items - B2B": 55
      },
      {
        "(Child) ASIN": "B001AD0HL8",
        "Title": "Ancient Minerals Magnesium Oil Spray Bottle of Pure Genuine Zechstein Magnesium Chloride - Topical Magnesium Supplement for Skin Application and Dermal Absorption (8 Fl Oz)",
        "Sessions": "6,927",
        "Session Percentage": "17.73%",
        "Page Views": "9,556",
        "Page Views Percentage": "16.14%",
        "Buy Box Percentage": "87%",
        "Units Ordered": "1,952",
        "Units Ordered - B2B": 25,
        "Unit Session Percentage": "28.18%",
        "Unit Session Percentage - B2B": "0.36%",
        "Ordered Product Sales": "$39,207.66 ",
        "Ordered Product Sales - B2B": "$496.43 ",
        "Total Order Items": "1,856",
        "Total Order Items - B2B": 25
      },
      {
        "(Child) ASIN": "B005F1ATJQ",
        "Title": "Ancient Minerals Magnesium Bath Flakes of Pure Genuine Zechstein Chloride - Resealable Magnesium Supplement Bag That Will Outperform Leading Epsom Salts (26.4 Ounce)",
        "Sessions": "3,300",
        "Session Percentage": "8.45%",
        "Page Views": "5,703",
        "Page Views Percentage": "9.63%",
        "Buy Box Percentage": "94%",
        "Units Ordered": "1,091",
        "Units Ordered - B2B": 24,
        "Unit Session Percentage": "33.06%",
        "Unit Session Percentage - B2B": "0.73%",
        "Ordered Product Sales": "$11,502.12 ",
        "Ordered Product Sales - B2B": "$245.68 ",
        "Total Order Items": "981",
        "Total Order Items - B2B": 22
      },
      {
        "(Child) ASIN": "B06XXP8YRL",
        "Title": "Ancient Minerals Magnesium Lotion of Pure Genuine Zechstein Magnesium Chloride - Best used for Topical Skin Application on Sensitive Skin (5oz)",
        "Sessions": "3,069",
        "Session Percentage": "7.85%",
        "Page Views": "4,368",
        "Page Views Percentage": "7.38%",
        "Buy Box Percentage": "90%",
        "Units Ordered": "1,702",
        "Units Ordered - B2B": 14,
        "Unit Session Percentage": "55.46%",
        "Unit Session Percentage - B2B": "0.46%",
        "Ordered Product Sales": "$35,842.91 ",
        "Ordered Product Sales - B2B": "$292.80 ",
        "Total Order Items": "1,536",
        "Total Order Items - B2B": 13
      },
      {
        "(Child) ASIN": "B00JFUD1OS",
        "Title": "Ancient Minerals Magnesium Bath Flakes Ultra with OptiMSM - Resealable Magnesium Supplement Bag of Zechstein Chloride with Proven Better Absorption Than Epsom Bath Salt (1.65 lb)",
        "Sessions": "1,893",
        "Session Percentage": "4.85%",
        "Page Views": "2,592",
        "Page Views Percentage": "4.38%",
        "Buy Box Percentage": "96%",
        "Units Ordered": "1,050",
        "Units Ordered - B2B": 18,
        "Unit Session Percentage": "55.47%",
        "Unit Session Percentage - B2B": "0.95%",
        "Ordered Product Sales": "$14,167.98 ",
        "Ordered Product Sales - B2B": "$245.22 ",
        "Total Order Items": "781",
        "Total Order Items - B2B": 11
      },
      {
        "(Child) ASIN": "B06XXR6PRD",
        "Title": "Ancient Minerals Magnesium Lotion ULTRA with MSM - Pure Genuine Zechstein Magnesium Lotion Supplement with MSM for Topical Application (5oz)",
        "Sessions": "2,285",
        "Session Percentage": "5.85%",
        "Page Views": "3,414",
        "Page Views Percentage": "5.77%",
        "Buy Box Percentage": "96%",
        "Units Ordered": "1,469",
        "Units Ordered - B2B": 10,
        "Unit Session Percentage": "64.29%",
        "Unit Session Percentage - B2B": "0.44%",
        "Ordered Product Sales": "$34,170.98 ",
        "Ordered Product Sales - B2B": "$230.49 ",
        "Total Order Items": "1,331",
        "Total Order Items - B2B": 10
      },
      {
        "(Child) ASIN": "B07G7GK2N1",
        "Title": "Enviromedica Terraflora Daily Care SBO Probiotic + Prebiotic Supplement - a Soil Based Shelf Stable Bacillus Spore Form Synbiotic formulated to Assist with Complete Gut Health (60ct)",
        "Sessions": "1,479",
        "Session Percentage": "3.79%",
        "Page Views": "2,126",
        "Page Views Percentage": "3.59%",
        "Buy Box Percentage": "89%",
        "Units Ordered": "623",
        "Units Ordered - B2B": 11,
        "Unit Session Percentage": "42.12%",
        "Unit Session Percentage - B2B": "0.74%",
        "Ordered Product Sales": "$32,322.64 ",
        "Ordered Product Sales - B2B": "$571.81 ",
        "Total Order Items": "566",
        "Total Order Items - B2B": 10
      },
      {
        "(Child) ASIN": "B06XXPLT2T",
        "Title": "Ancient Minerals Magnesium Bath Flakes of Pure Genuine Zechstein Chloride - Resealable Magnesium Supplement Bag That Will Outperform Leading Epsom Salts (4.4 lb)",
        "Sessions": "2,140",
        "Session Percentage": "5.48%",
        "Page Views": "4,143",
        "Page Views Percentage": "7.00%",
        "Buy Box Percentage": "94%",
        "Units Ordered": "954",
        "Units Ordered - B2B": 9,
        "Unit Session Percentage": "44.58%",
        "Unit Session Percentage - B2B": "0.42%",
        "Ordered Product Sales": "$20,184.58 ",
        "Ordered Product Sales - B2B": "$187.56 ",
        "Total Order Items": "895",
        "Total Order Items - B2B": 8
      },
      {
        "(Child) ASIN": "B008JSJ9HU",
        "Title": "Ancient Minerals Magnesium Oil Spray Ultra with MSM - a Pure Zechstein Topical Magnesium Chloride Supplement with The Added Benefits of OptiMSM (8oz)",
        "Sessions": "1,303",
        "Session Percentage": "3.33%",
        "Page Views": "1,847",
        "Page Views Percentage": "3.12%",
        "Buy Box Percentage": "94%",
        "Units Ordered": "378",
        "Units Ordered - B2B": 7,
        "Unit Session Percentage": "29.01%",
        "Unit Session Percentage - B2B": "0.54%",
        "Ordered Product Sales": "$8,735.35 ",
        "Ordered Product Sales - B2B": "$162.47 ",
        "Total Order Items": "355",
        "Total Order Items - B2B": 7
      },
      {
        "(Child) ASIN": "B00BN9PFUW",
        "Title": "Ancient Minerals Goodnight Magnesium Lotion with Melatonin and OptiMSM - Night Cream of Topical Nighttime Moisturizing Lotion formulated for Bedtime Absorption (2.5oz)",
        "Sessions": "775",
        "Session Percentage": "1.98%",
        "Page Views": "1,107",
        "Page Views Percentage": "1.87%",
        "Buy Box Percentage": "88%",
        "Units Ordered": "354",
        "Units Ordered - B2B": 10,
        "Unit Session Percentage": "45.68%",
        "Unit Session Percentage - B2B": "1.29%",
        "Ordered Product Sales": "$10,815.03 ",
        "Ordered Product Sales - B2B": "$305.79 ",
        "Total Order Items": "302",
        "Total Order Items - B2B": 7
      },
      {
        "(Child) ASIN": "B06XXN4T98",
        "Title": "Ancient Minerals Magnesium Oil Spray Bottle of Pure Genuine Zechstein Magnesium Chloride - Topical Magnesium Supplement for Skin Application and Dermal Absorption (4oz)",
        "Sessions": "1,798",
        "Session Percentage": "4.60%",
        "Page Views": "2,604",
        "Page Views Percentage": "4.40%",
        "Buy Box Percentage": "95%",
        "Units Ordered": "623",
        "Units Ordered - B2B": 25,
        "Unit Session Percentage": "34.65%",
        "Unit Session Percentage - B2B": "1.39%",
        "Ordered Product Sales": "$7,879.18 ",
        "Ordered Product Sales - B2B": "$319.92 ",
        "Total Order Items": "572",
        "Total Order Items - B2B": 6
      },
      {
        "(Child) ASIN": "B00X7RCW4A",
        "Title": "Enviromedica Magnetic Clay Natural Detox Bath Cleanse - Ancient Sodium and Calcium Bentonite Clay Powder with Himalayan Pink Salt for Detoxification of Harmful Toxins and Environmental Allergens",
        "Sessions": "1,655",
        "Session Percentage": "4.24%",
        "Page Views": "2,397",
        "Page Views Percentage": "4.05%",
        "Buy Box Percentage": "93%",
        "Units Ordered": "411",
        "Units Ordered - B2B": 5,
        "Unit Session Percentage": "24.83%",
        "Unit Session Percentage - B2B": "0.30%",
        "Ordered Product Sales": "$17,348.69 ",
        "Ordered Product Sales - B2B": "$210.23 ",
        "Total Order Items": "390",
        "Total Order Items - B2B": 5
      },
      {
        "(Child) ASIN": "B00JIN7DVY",
        "Title": "Ancient Minerals Magnesium Gel Ultra with OptiMSM and Aloe Vera - Topical Magnesium Gel Formula with MSM Best Used for Dermal Skin Absorption and Massage Therapy (8oz)",
        "Sessions": "570",
        "Session Percentage": "1.46%",
        "Page Views": "785",
        "Page Views Percentage": "1.33%",
        "Buy Box Percentage": "88%",
        "Units Ordered": "206",
        "Units Ordered - B2B": 3,
        "Unit Session Percentage": "36.14%",
        "Unit Session Percentage - B2B": "0.53%",
        "Ordered Product Sales": "$4,794.75 ",
        "Ordered Product Sales - B2B": "$69.12 ",
        "Total Order Items": "180",
        "Total Order Items - B2B": 3
      },
      {
        "(Child) ASIN": "B07H7VM5Q8",
        "Title": "Enviromedica Tracheal Cartilage Collagen Supplement Capsules of Undenatured Type II Bovine Collagen Protein sourced from Grass Fed New Zealand Beef (120ct)",
        "Sessions": "865",
        "Session Percentage": "2.21%",
        "Page Views": "1,275",
        "Page Views Percentage": "2.15%",
        "Buy Box Percentage": "91%",
        "Units Ordered": "313",
        "Units Ordered - B2B": 2,
        "Unit Session Percentage": "36.18%",
        "Unit Session Percentage - B2B": "0.23%",
        "Ordered Product Sales": "$12,998.97 ",
        "Ordered Product Sales - B2B": "$85.24 ",
        "Total Order Items": "267",
        "Total Order Items - B2B": 2
      },
      {
        "(Child) ASIN": "B082MT873N",
        "Title": "Enviromedica Terraflora Deep Immune SBO Probiotic + Prebiotic Supplement - a Soil Based Shelf Stable Bacillus Spore Form Synbiotic with LC-Plasma - a Powerful Immune Booster (60ct)",
        "Sessions": "665",
        "Session Percentage": "1.70%",
        "Page Views": "954",
        "Page Views Percentage": "1.61%",
        "Buy Box Percentage": "93%",
        "Units Ordered": "170",
        "Units Ordered - B2B": 3,
        "Unit Session Percentage": "25.56%",
        "Unit Session Percentage - B2B": "0.45%",
        "Ordered Product Sales": "$10,454.13 ",
        "Ordered Product Sales - B2B": "$190.86 ",
        "Total Order Items": "144",
        "Total Order Items - B2B": 2
      },
      {
        "(Child) ASIN": "B082MTLLRH",
        "Title": "Enviromedica Terraflora Advanced Care SBO Probiotic + Prebiotic Supplement - a Soil Based Shelf Stable Bacillus Spore Synbiotic with Patented PreforPro Phage Complex (60ct)",
        "Sessions": "325",
        "Session Percentage": "0.83%",
        "Page Views": "497",
        "Page Views Percentage": "0.84%",
        "Buy Box Percentage": "92%",
        "Units Ordered": "77",
        "Units Ordered - B2B": 2,
        "Unit Session Percentage": "23.69%",
        "Unit Session Percentage - B2B": "0.62%",
        "Ordered Product Sales": "$4,724.44 ",
        "Ordered Product Sales - B2B": "$123.71 ",
        "Total Order Items": "71",
        "Total Order Items - B2B": 2
      },
      {
        "(Child) ASIN": "B06XXPSJGT",
        "Title": "Ancient Minerals Magnesium Oil Spray Ultra with MSM - a Pure Zechstein Topical Magnesium Chloride Supplement with The Added Benefits of OptiMSM (4oz)",
        "Sessions": "788",
        "Session Percentage": "2.02%",
        "Page Views": "1,106",
        "Page Views Percentage": "1.87%",
        "Buy Box Percentage": "95%",
        "Units Ordered": "207",
        "Units Ordered - B2B": 1,
        "Unit Session Percentage": "26.27%",
        "Unit Session Percentage - B2B": "0.13%",
        "Ordered Product Sales": "$2,828.55 ",
        "Ordered Product Sales - B2B": "$12.95 ",
        "Total Order Items": "186",
        "Total Order Items - B2B": 1
      },
      {
        "(Child) ASIN": "B07H7VBFF1",
        "Title": "Enviromedica Freeze Dried Beef Liver Natural Energy Supplement Capsules of Pure Grass-Fed, Pastured, New Zealand Bovine with Preformed Vitamin A (180ct)",
        "Sessions": "712",
        "Session Percentage": "1.82%",
        "Page Views": "1,037",
        "Page Views Percentage": "1.75%",
        "Buy Box Percentage": "91%",
        "Units Ordered": "232",
        "Units Ordered - B2B": 1,
        "Unit Session Percentage": "32.58%",
        "Unit Session Percentage - B2B": "0.14%",
        "Ordered Product Sales": "$7,254.81 ",
        "Ordered Product Sales - B2B": "$29.95 ",
        "Total Order Items": "204",
        "Total Order Items - B2B": 1
      },
      {
        "(Child) ASIN": "B07HZPZKNC",
        "Title": "Ancient Minerals Magnesium Oil Spray Sensitive - All-New Sensitive Formula with Allantoin, Organic Chamomile, and Organic Aloe Vera (4oz)",
        "Sessions": "454",
        "Session Percentage": "1.16%",
        "Page Views": "687",
        "Page Views Percentage": "1.16%",
        "Buy Box Percentage": "92%",
        "Units Ordered": "166",
        "Units Ordered - B2B": 1,
        "Unit Session Percentage": "36.56%",
        "Unit Session Percentage - B2B": "0.22%",
        "Ordered Product Sales": "$2,064.24 ",
        "Ordered Product Sales - B2B": "$12.98 ",
        "Total Order Items": "155",
        "Total Order Items - B2B": 1
      },
      {
        "(Child) ASIN": "B082XHGHM3",
        "Title": "Enviromedica Freeze-Dried Bone Marrow Complex with Cartilage and MCHA Whole Bone from Grass-Fed Pastured New Zealand Bovine (120ct)",
        "Sessions": "450",
        "Session Percentage": "1.15%",
        "Page Views": "720",
        "Page Views Percentage": "1.22%",
        "Buy Box Percentage": "93%",
        "Units Ordered": "121",
        "Units Ordered - B2B": 2,
        "Unit Session Percentage": "26.89%",
        "Unit Session Percentage - B2B": "0.44%",
        "Ordered Product Sales": "$3,752.36 ",
        "Ordered Product Sales - B2B": "$63.64 ",
        "Total Order Items": "108",
        "Total Order Items - B2B": 1
      },
      {
        "(Child) ASIN": "1450283543",
        "Title": "Transdermal Magnesium Therapy: A New Modality for the Maintenance of Health",
        "Sessions": "250",
        "Session Percentage": "0.64%",
        "Page Views": "534",
        "Page Views Percentage": "0.90%",
        "Buy Box Percentage": "97%",
        "Units Ordered": "31",
        "Units Ordered - B2B": 0,
        "Unit Session Percentage": "12.40%",
        "Unit Session Percentage - B2B": "0.00%",
        "Ordered Product Sales": "$527.24 ",
        "Ordered Product Sales - B2B": "$0.00 ",
        "Total Order Items": "31",
        "Total Order Items - B2B": 0
      },
      {
        "(Child) ASIN": "B06XXN4TNR",
        "Title": "Ancient Minerals Magnesium Oil Refill Bottle of Pure Genuine Zechstein Magnesium Chloride - Topical Magnesium Supplement for Skin Application and Dermal Absorption (33.8oz)",
        "Sessions": "832",
        "Session Percentage": "2.13%",
        "Page Views": "1,252",
        "Page Views Percentage": "2.11%",
        "Buy Box Percentage": "96%",
        "Units Ordered": "168",
        "Units Ordered - B2B": 0,
        "Unit Session Percentage": "20.19%",
        "Unit Session Percentage - B2B": "0.00%",
        "Ordered Product Sales": "$7,099.63 ",
        "Ordered Product Sales - B2B": "$0.00 ",
        "Total Order Items": "157",
        "Total Order Items - B2B": 0
      },
      {
        "(Child) ASIN": "B06XXSYX2W",
        "Title": "Ancient Minerals Magnesium Oil Ultra with OptiMSM, Refill 33.8 oz. - Pure Genuine Zechstein Magnesium Chloride Supplement with MSM - Best Topical Skin Application for Dermal Absorption",
        "Sessions": "336",
        "Session Percentage": "0.86%",
        "Page Views": "500",
        "Page Views Percentage": "0.84%",
        "Buy Box Percentage": "94%",
        "Units Ordered": "107",
        "Units Ordered - B2B": 0,
        "Unit Session Percentage": "31.85%",
        "Unit Session Percentage - B2B": "0.00%",
        "Ordered Product Sales": "$4,982.48 ",
        "Ordered Product Sales - B2B": "$0.00 ",
        "Total Order Items": "89",
        "Total Order Items - B2B": 0
      },
      {
        "(Child) ASIN": "B07JH84532",
        "Title": "Ancient Minerals Magnesium Oil Spray Sensitive Plus - All-New Sensitive+ Formula Oil with Avena Sativa (Oat Aventhramides), Nopal Cactus, Organic Chamomile, and Allantoin (4oz)",
        "Sessions": "182",
        "Session Percentage": "0.47%",
        "Page Views": "291",
        "Page Views Percentage": "0.49%",
        "Buy Box Percentage": "97%",
        "Units Ordered": "47",
        "Units Ordered - B2B": 0,
        "Unit Session Percentage": "25.82%",
        "Unit Session Percentage - B2B": "0.00%",
        "Ordered Product Sales": "$734.27 ",
        "Ordered Product Sales - B2B": "$0.00 ",
        "Total Order Items": "40",
        "Total Order Items - B2B": 0
      },
      {
        "(Child) ASIN": "B07KBDYKRK",
        "Title": "Enviromedica Cartilage Collagen Supplement Capsules",
        "Sessions": "1",
        "Session Percentage": "0.00%",
        "Page Views": "1",
        "Page Views Percentage": "0.00%",
        "Buy Box Percentage": "0%",
        "Units Ordered": "0",
        "Units Ordered - B2B": 0,
        "Unit Session Percentage": "0.00%",
        "Unit Session Percentage - B2B": "0.00%",
        "Ordered Product Sales": "$0.00 ",
        "Ordered Product Sales - B2B": "$0.00 ",
        "Total Order Items": "0",
        "Total Order Items - B2B": 0
      },
      {
        "(Child) ASIN": "B07KY3N9SF",
        "Title": "Ancient Minerals Inflatable Foot Bath Kit with Single-Use Magnesium Chloride Flakes Pouch - Great for Travel or at-Home Spa",
        "Sessions": "132",
        "Session Percentage": "0.34%",
        "Page Views": "186",
        "Page Views Percentage": "0.31%",
        "Buy Box Percentage": "94%",
        "Units Ordered": "11",
        "Units Ordered - B2B": 0,
        "Unit Session Percentage": "8.33%",
        "Unit Session Percentage - B2B": "0.00%",
        "Ordered Product Sales": "$210.26 ",
        "Ordered Product Sales - B2B": "$0.00 ",
        "Total Order Items": "11",
        "Total Order Items - B2B": 0
      },
      {
        "(Child) ASIN": "B07MR2MDW8",
        "Title": "Ancient Minerals Magnesium Bath Flakes Single-Use Magnesium Chloride Pouches (0.33lb Bag, Pack of 6)",
        "Sessions": "63",
        "Session Percentage": "0.16%",
        "Page Views": "91",
        "Page Views Percentage": "0.15%",
        "Buy Box Percentage": "93%",
        "Units Ordered": "12",
        "Units Ordered - B2B": 0,
        "Unit Session Percentage": "19.05%",
        "Unit Session Percentage - B2B": "0.00%",
        "Ordered Product Sales": "$238.79 ",
        "Ordered Product Sales - B2B": "$0.00 ",
        "Total Order Items": "11",
        "Total Order Items - B2B": 0
      },
      {
        "(Child) ASIN": "B082MSTTPX",
        "Title": "Enviromedica Terraflora Women's Daily SBO Probiotic + Prebiotic Supplement - a Soil Based Bacillus Spore Form Synbiotic with Organic Cranberry to Support and a Healthy Urinary Tract (60ct)",
        "Sessions": "206",
        "Session Percentage": "0.53%",
        "Page Views": "304",
        "Page Views Percentage": "0.51%",
        "Buy Box Percentage": "94%",
        "Units Ordered": "29",
        "Units Ordered - B2B": 0,
        "Unit Session Percentage": "14.08%",
        "Unit Session Percentage - B2B": "0.00%",
        "Ordered Product Sales": "$1,515.14 ",
        "Ordered Product Sales - B2B": "$0.00 ",
        "Total Order Items": "29",
        "Total Order Items - B2B": 0
      },
      {
        "(Child) ASIN": "B082XJVB9S",
        "Title": "Enviromedica Grass-Fed Organ Complex: Freeze-Dried Beef Liver, Kidney, Heart, and Pancreas (150ct)",
        "Sessions": "403",
        "Session Percentage": "1.03%",
        "Page Views": "627",
        "Page Views Percentage": "1.06%",
        "Buy Box Percentage": "91%",
        "Units Ordered": "95",
        "Units Ordered - B2B": 0,
        "Unit Session Percentage": "23.57%",
        "Unit Session Percentage - B2B": "0.00%",
        "Ordered Product Sales": "$2,970.02 ",
        "Ordered Product Sales - B2B": "$0.00 ",
        "Total Order Items": "81",
        "Total Order Items - B2B": 0
      },
     ],
   
  };